version: "3"

services:
  api:
    image: node:16-alpine
    volumes:
      - ./:/project:rw
    working_dir: /project
    entrypoint: sh -c "npx nx serve api"
  app:
    image: node:16-alpine
    working_dir: /project
    volumes:
      - ./:/project:rw
    command: sh -c "npx nx serve urlshortener --port=8000 --host 0.0.0.0"
