version: "3"

services:
  api:
    container_name: api
    build:
      context: dist/apps/api
      dockerfile: $PWD/apps/api/Dockerfile
    expose:
      - 9000
    depends_on:
      - postgres
  app:
    image: nginx:alpine
    container_name: app
    depends_on:
      - api
    volumes:
      - ./dist/apps/urlshortener:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ****
      POSTGRES_PASSWORD: ****
      CONTAINER_NAME: postgres
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
