version: "3"

services:
  api:
    container_name: api
    build:
      context: dist/apps/api
      dockerfile: $PWD/apps/api/Dockerfile
    expose:
      - 9000
  app:
    image: nginx:alpine
    container_name: app
    depends_on:
      - api
    volumes:
      - ./dist/apps/urlshortener:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
